name: Reusable Build

on:
  workflow_call:

jobs:
  build:
    name: Build and Push Docker Images
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set Git Commit SHA
      id: vars
      run: echo "git_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Packages (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Todofy Main App Docker image
      run: |
        docker build \
          --build-arg GIT_COMMIT=${{ steps.vars.outputs.git_commit_sha }} \
          -t ghcr.io/${{ github.repository_owner }}/todofy:latest \
          -f Dockerfile .

    - name: Build Todofy LLM Service Docker image
      run: |
        docker build \
          --build-arg GIT_COMMIT=${{ steps.vars.outputs.git_commit_sha }} \
          -t ghcr.io/${{ github.repository_owner }}/todofy-llm:latest \
          -f llm/Dockerfile .

    - name: Build Todofy Todo Service Docker image
      run: |
        docker build \
          --build-arg GIT_COMMIT=${{ steps.vars.outputs.git_commit_sha }} \
          -t ghcr.io/${{ github.repository_owner }}/todofy-todo:latest \
          -f todo/Dockerfile .

    - name: Build Todofy Database Service Docker image
      run: |
        docker build \
          --build-arg GIT_COMMIT=${{ steps.vars.outputs.git_commit_sha }} \
          -t ghcr.io/${{ github.repository_owner }}/todofy-database:latest \
          -f database/Dockerfile .

    - name: Push Docker images to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/todofy:latest
        docker push ghcr.io/${{ github.repository_owner }}/todofy-llm:latest
        docker push ghcr.io/${{ github.repository_owner }}/todofy-todo:latest
        docker push ghcr.io/${{ github.repository_owner }}/todofy-database:latest
